aws:
  version: latest
  region: "%env(AWS_REGION)%"
  DynamoDb:
    region: "%env(AWS_REGION)%"

when@dev:
  aws:
    version: latest
    region: "%env(AWS_REGION)%"
    credentials:
      key: "%env(AWS_ACCESS_KEY_ID)%"
      secret: "%env(AWS_SECRET_ACCESS_KEY)%"
    DynamoDb:
      region: "%env(AWS_REGION)%"
      endpoint: '%env(DYNAMODB_ENDPOINT)%'
